version: '3'

vars:
  NAME: 'Jordan Hasgul'
  USER: 'jkhasgul'
  EMAIL: 'jkhasgul@gmail.com'

tasks:

  setup-deps:
    deps: [install-deps]
    cmds:
      - |
        set -e
        cd dotfiles
        for dir in *; do
          stow -t $HOME --adopt $dir
        done

  install-deps:
    deps: [install-kubectl, install-docker, install-go, install-github, install-neovim, install-tmux, install-zsh, install-ghostty, install-stow, install-git]

   install-kubectl:
    deps: [install-brew]
    cmds:
      - brew install kubernetes-cli

  install-docker:
    deps: [install-brew]
    cmds:
      - brew install --cask docker

  install-go:
    deps: [install-brew]
    cmds:
      - brew install go

        
  install-github:
    deps: [install-brew]
    cmds:
      - brew install --cask github

  install-neovim:
    deps: [install-brew]
    cmds:
      - brew install neovim

  install-tmux:
    deps: [install-brew]
    cmds:
      - brew install tmux

  install-zsh:
    deps: [install-brew]
    cmds:
      - brew install zsh
      - sudo sh -c "echo $(which zsh) >> /etc/shells"
      - sudo chsh -s $(which zsh) {{.USER}}
      
  install-ghostty:
    deps: [install-brew]
    cmds:
      - brew install --cask ghostty
  
  install-stow:
    deps: [install-brew]
    cmds:
      - brew install stow

  install-brew:
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/{{.USER}}/.bashrc
   